name: ci

on: push

jobs:
  name: job1
  runs-on: ubuntu-latest
  run: date

  name: job2
  runs-on: windows-latest
  run: date /t

  name: job3
  runs-on: macos-latest
  run: date

  name: job4
  runs-on: ubuntu-latest
  needs: [job1, job2, job3]