name: ci

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      run: date

  job2:
    runs-on: windows-latest
    steps:
      run: date /t

  job3:
    runs-on: macos-latest
    steps:
      run: date

  job4:
    runs-on: ubuntu-latest
    steps:
      needs: [job1, job2, job3]