name: ci

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
        run: date

  job2:
    name: Second job
    runs-on: windows-latest
    steps:
        uses: actions/checkout@v2
        run: date /t

  job3:
    name: Third job
    runs-on: macos-latest
    steps:
        uses: actions/checkout@v2
        run: date

  job4:
    name: Fourth job
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
        needs: [job1, job2, job3]
        run: date